// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Alt text and focal points live in content/images.ts, which reads this.

export type GeneratedImage = {
  slug: string;
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  origin: "theme" | "library";
};

export const GENERATED_IMAGES = [
  {
    "slug": "28f5060c-884c-4271-9c9b-d8fc9f06706e",
    "src": "/images/28f5060c-884c-4271-9c9b-d8fc9f06706e.webp",
    "width": 1284,
    "height": 1925,
    "blurDataURL": "data:image/webp;base64,UklGRsgAAABXRUJQVlA4ILwAAABwBQCdASoUAB4APu1qrlCppiQiqAqpMB2JaQAD51DwSk7iDE1xbr21o86f/isDmgEyh3ggAP5s/zDr5u0wMAAOgkBl6nZ1VbkMQK4ohhN3ddQyFSKOlAP6ZtSUIoYfB5Qk8BanQhELYBHKayDRIpeY9nast0J6HJepcn+7JdDGNVg9qfR7RoQf1FO9LAo3NUf/SKLWE1b1SwvpLqcDnrnhCG11U7LNqnRl/fUtY2ZD2LdA3wzTwuje2kgAAA==",
    "origin": "library"
  },
  {
    "slug": "8007a6c2-081a-4943-9f77-4432c0a125b1",
    "src": "/images/8007a6c2-081a-4943-9f77-4432c0a125b1.webp",
    "width": 1284,
    "height": 1925,
    "blurDataURL": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAAAQBQCdASoUAB4APu1urlKppiQiqAgBMB2JYwDBzYxiUUWYesYefWljW+ReA4+VgQkAAP6t0VmT2frdcni+2b406+OmreADbXAE63oSTVAO4jVUPeBkjTz1M/xlz3KyscpH2zCRhkFMAdnIvhnLteSZYPynNRy+AH7cbN6wUuc2XamFT2BrHcmHZPnnaiZxzPzpTY8PIJ+7bvVv752aZhDUz24mY2SfnSnyWHrNQRwCJYw/O0vWPabwymTD0MD1gOXbwxKlwSGP5bO17SzFf5+M/pC6AAAA",
    "origin": "library"
  },
  {
    "slug": "91ba5be9-af7d-4ff7-bc5b-20b251fd06a8",
    "src": "/images/91ba5be9-af7d-4ff7-bc5b-20b251fd06a8.webp",
    "width": 1968,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBACdASoUABgAPu1ur1IppiQiqAgBMB2JaQAAIe1c7/VhoPS6jGVktQAA/vDf9wscgCynV54hPqhLjFbOzUnUCz2iDPxBjJ+M+rCHbSZvXGSdi1i8B+IJQ3bIPzwSSnfqZn36aw6BpbZoRtDhsSXIIL6jpBPCEcGF8UkhIfKZCMAlflOG9vMyzvWD4RGcnMr1rY9qAoP1wilO6XvUnzeEM0FXAAAA",
    "origin": "library"
  },
  {
    "slug": "9a2500e5-c44d-404d-b0e0-980007fd4a93",
    "src": "/images/9a2500e5-c44d-404d-b0e0-980007fd4a93.webp",
    "width": 1284,
    "height": 1925,
    "blurDataURL": "data:image/webp;base64,UklGRvYAAABXRUJQVlA4IOoAAACwBQCdASoUAB4APu1kqE2ppaOiMAgBMB2JZgCdMzQ5aBo3WVb0BKHDxV7dSBJo+4U0SRZzbKAA+D4xjQGFq3TS82kdxecu0XN11J0dayp5g9aAEkSQE77Cf4MsJyuB0KvjtNy3ZIGK3uvBBm9cEhkX3hLbh9MHbi039M8skVBBmK2GaSkSQAhdNqE1cFZCf4Doo8phg3E0vNE0NYegd0Tcfg1MkeNVhonkXJ5I9IA9ibf+RJdAF5bXDMl5xAjLAzTn4BTkVMX6O1IDFi5vY9DWcDfJ+kWBGKV8tCfpE3BUqey8IQawaMAAAAA=",
    "origin": "library"
  },
  {
    "slug": "a13b0d35-973d-4600-8ab8-7c83c1ffc826",
    "src": "/images/a13b0d35-973d-4600-8ab8-7c83c1ffc826.webp",
    "width": 1284,
    "height": 1925,
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAwBQCdASoUAB4APu1irFAppSQisBgIATAdiWcAAI9QpgT5vI7RfHY76tWW5DgUMpdKKAD+u67oKzzE47D+mZz6g2NE22JPFYNXtrOMdcnWmEh/V7okZJgJCuwti9ZBbLZWY5k4TO5SsUZdSX6JMk8BAk5spG2YAAA=",
    "origin": "library"
  },
  {
    "slug": "cb45229f-fe11-41a2-937d-79091429ee2d",
    "src": "/images/cb45229f-fe11-41a2-937d-79091429ee2d.webp",
    "width": 1067,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACwBQCdASoUAB4APu1kqE2ppaOiMAgBMB2JbACxHt69H7MAYR5AXjDGCTNnGfMq5GjCgLeUnyAA/ujNe8CcsGPJYM7V4UiDW/FVJN/D6DCiILlF3J8OFyZLUEYiZ5IVVbf+2KatKi5BJ6Sd3h0Nw9MKYnJRIZblG0DqV8UoI7IFerNn/mEsxmtpy4klOPv45d/M5n4WBe4rUK5yIxqRx0NmkjcQEuu3pXDxvfigAAA=",
    "origin": "library"
  },
  {
    "slug": "h-a-bm-48",
    "src": "/images/h-a-bm-48.webp",
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRuQAAABXRUJQVlA4INgAAACQBQCdASoUAB4APu1mqk2ppaQiMAgBMB2JZQCo9BxsWAj8WuAHyl7VkKIHCbBN1rDMTcHcgADMlzadStvKoMO/xQTABHi8Q1/exJrgmPVbaRLJHzEJaNt6E8FCQ3yD/br5AN4zvZwxjZQCEXBSN7mdCK5RpiY33jTvAZkIxK1M4yoZvK/husyyTJ8UzqK4FXLJjLqXIL61uWj8nCHqHezF9ccfy96sVmP3jbIYJDm6g9N+OsqBNcyNlZydNtYQxXTgsuuOF3WmUHPEVoUOLBdyxvV23UtxAAA=",
    "origin": "library"
  },
  {
    "slug": "h-a-bm-56",
    "src": "/images/h-a-bm-56.webp",
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAABwBQCdASoUAB4APu1sq08ppqOiMBgIATAdiWMAyNWMMVm0y2dv2e5NgAScPFwicCIgdAGAAP70z2JR2ztpUhTxZ7Ae1DdzUbCe9x0aOE6BOqkBV0VaOd92W9gl13Stn9tcsugCmpknDq2yUi653EiH7tDL1qfKWwROdAXnuuOrMLhMDQs8M9HSnuoXF3P6vIsEagwEHi5V8BilLcuZa8ze7uHuRN/Q3YJeknvBVZ/0rGEGaQDPNByzkJHNvrvBCWfHXkHANUAVcHom8EwAAA==",
    "origin": "library"
  },
  {
    "slug": "img-0896",
    "src": "/images/img-0896.webp",
    "width": 1366,
    "height": 2048,
    "blurDataURL": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAACQBQCdASoUAB4APu1oq08ppiOiMBgIATAdiWkAAI1lFSmlooQuaPaEgJw0iTN+E78HY8/QAAD+6lWhdrSS5qC+l+jCpk5i9NdY4gGGatSzRhfbjjYAeKYycxaA+RkSzrlM/15CDcjE9GJz6bIF/jh532IxCfd+AEvk8dh8xLfzEviS5WyAq4Mw8IJwK44ok23hIJ92zh7XwJ0NKoGdDBy501iIpCsgUjLH3wVfahj39Q44oPksm6G3z+sXmqS+AYzwUw/U+dSzzgAA",
    "origin": "library"
  },
  {
    "slug": "img-0908",
    "src": "/images/img-0908.webp",
    "width": 1350,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRu4AAABXRUJQVlA4IOIAAADQBQCdASoUACQAPu1kqE8ppSOiKqwBMB2JZQC7ABXBueKZSyiHj1Y4hR69cgOkQlM57GJ9bBoAAP6IMLHJOJfDHwzKFioY+j88icBuurMCGLMw3cW+72gyKjI82iYG5Uv9Rgi1IbaG7V63rdTDA8a5OZCLMNe2gUviL4ayqyyQHPKWmtO/jUh1LMJss9MjxPKdnykfykPdHXLnUS/3jWeeWIC8kX7l33aFROR5CSK6nWZT5/iXel/mx/GKpK+shzI2m32Pw/jGpSaJ47Fof9WnjWS6YZvPxHdTRQMOjHlSAAAA",
    "origin": "library"
  },
  {
    "slug": "img-1122",
    "src": "/images/img-1122.webp",
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRtgAAABXRUJQVlA4IMwAAADQBQCdASoUAB4APu1orE8ppiQiMBgIATAdiWMAsR8iBnIuQnCWVJteBqpuLnfDyV7vL1TdtttAAP7TlS0iD3lKMSuwBB1zVCF+/4C7ZMI0pInBmWh40oYnNo6eb8eRb6jP/GR1/Ck6GHh4rJGl9a55ZiFwH0rqsT7wDiZeZCFqDETmIxYVvk10E8TKMofIB7xU9k2BzYApqqJGE6FzTLeV0p4yvz9cIHyZh+qsojGm8dogOWNjF+28joGR1HlxngD02B2rV9yd+PDVYAA=",
    "origin": "library"
  },
  {
    "slug": "img-1123",
    "src": "/images/img-1123.webp",
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAAAQBgCdASoUAB4APu1qr1AppaSiqAqpMB2JYwCo9Y0DWwXE+mGIa/i7C+Gz3h4xXMJ/ZyFnbyKRYgAA/tSbj7lwf+sy/RpzLz8mXJj6YEuWEXOh8Mhuyldb2Bc46TGCrEoxjAikxzWbKY9+DFelfT3pkSXE/qgM2rTN9zJULG3qhdEIeTNRttZqJ8OWQlbct8xiuZiVy0fUq0oLiV7Yozfdf+wgxD3kB5xWOdFsQTz6/DGoOT0OxmTdwTwr9jnVMl4nwUOzncDOJR0JuhM7aBHHUTFmjQAA",
    "origin": "library"
  },
  {
    "slug": "img-1127",
    "src": "/images/img-1127.webp",
    "width": 1601,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRtAAAABXRUJQVlA4IMQAAACwBQCdASoUAB4APu1iqU2ppaOiMAgBMB2JZQCsAdwLhjZMmojycl0u4fdoXVPn0oypIt/CYAAA/oIYKBJx4N/MCpbAixG8BU1T2ONLdaI1qkjE7PYgzi4mM/LaOEfBTBNZArH0fTG2yxUtWDN3bKzp4U/JmBBWxR60qympRqWxJhTmvr7YR3axyXt3iHKeTMoOeaARtWLrcewG3nfC+ZQt+I1yW1Lova2kO+pLHlTRLJAir+XtaO3XlXXkclTT0lLrgAAA",
    "origin": "library"
  },
  {
    "slug": "img-4310",
    "src": "/images/img-4310.webp",
    "width": 1463,
    "height": 2048,
    "blurDataURL": "data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAADQBQCdASoUABwAPu1iq1AppSOisBgIATAdiWUAygAN2lOch1XZR12aRsb8+lXQ72qDjtL2JHygAPP5LdivY4u0iSrU1hMa5v8x9nt9ZIP3cGLlm0wl6rTJuU7LJb9qaQejaa9OB3zKv8qVnbwutu89EEfzEucDl9fhwzzTfjAdZ0Yie84wWFYubaZdKEB/VfCd1wPy8Tmlr8D3zdsq33h8gJesFfKL6g0+daRBzqsAAA==",
    "origin": "library"
  },
  {
    "slug": "img-4311",
    "src": "/images/img-4311.webp",
    "width": 1463,
    "height": 2048,
    "blurDataURL": "data:image/webp;base64,UklGRt4AAABXRUJQVlA4INIAAABwBQCdASoUABwAPu1ur1IppiQiqAgBMB2JQBllsaLMi1PWem6erX89FaoXK9Ucnx8OUagAAP3rX3fcHfpJ9TnBvbEDFHvzZ3yreultX61XjjiKzGj1ai35LYwmapy6+DdFQ7W3F3EQculN8m2enqBm1yDvWMI1UlYsa/86uCfrseq4RenILWGXf4Rfb+LpeesYWDOlivnJ3TgkVpQjUIwFBYh5g2ripnItXF444CQy5WvWhczT5ZpqRvr02ZXCujCKsIUbn1Mswlk9SQHNbQUAAAA=",
    "origin": "library"
  },
  {
    "slug": "img-6078",
    "src": "/images/img-6078.webp",
    "width": 2400,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JZACdMoGv/gQF91uQLkJPz+vC8CAA/uuLuWFgDN3zPPJoAlH8A97ufTmVQ7+DGVMUe3aCGcuJ/Bh6NJ+cRK+m4hcOGMtV0zbcF/xErfliK8FWbIeHREEj10cKs2OGsRHet68Mb8GHq0zdNuIfy2txNKUdAOsIlMFBle8i01CO5h8nTUrArwAA",
    "origin": "library"
  },
  {
    "slug": "img-7027",
    "src": "/images/img-7027.webp",
    "width": 1800,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBACdASoUABsAPu1wsFIppiSiqAgBMB2JQBYdggq7sFjaVtHpEJI0lltP2Y7n4AD+u1CNTgljEahdaS0lJCaRoYUUYImXyo+rm4Gy6ePmTG5BQ2iW0E3Tg2xhEvsfiRxb0f82AfwEpfIYoJS9LrlLlL1TudGbqbIWKlgRn/hnHcz6kEOuy0kDQvGBQ2r6jv6lJN+oH2IOXiVRbXHG8qjijHKlxMAA",
    "origin": "library"
  },
  {
    "slug": "img-7028",
    "src": "/images/img-7028.webp",
    "width": 1800,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAQBQCdASoUABsAPu1qsFAppaSiqAqpMB2JYwC06A43BBrtX6V25TqGlx28uhyR8OZcAP0hIHdh8Twk/BAPBugOydwVpsSOG6qz2pwv1LzvqNvLyvaYJrVlZ35EsMhR+BZquVINxmbOc24OcRFTh+ndTF1vmllAwBpOwtsSebtjcNLhQo5dBTydkdREC6zG1RQ53d+EXxV8Ek4Jer/qCXr8ckK8AAAA",
    "origin": "library"
  },
  {
    "slug": "img-7029",
    "src": "/images/img-7029.webp",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAACwBQCdASoUABsAPu1sq1EppaOiqAqpMB2JYwCdAA95KfbpwOXEudYErMK7WQCISbML74KGGAAA/nkYVKHHQZ4e5m4ZAYNmqhPxbg7rdvj6nizdhVV/oA7CarRQFI5YvIvMuKj7rDZzwvAChM8kuQyS7zJvGqgf98prtwIsYqxIjwEvqz8HYKQW9iaX1GdAkJktbgHDkNY52tnRdz+VkY4xbu9QWPmJSYQTEjwAAAA=",
    "origin": "library"
  },
  {
    "slug": "img-7030",
    "src": "/images/img-7030.webp",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAADQBACdASoUABsAPu1irFAppSQisBgIATAdiWkAABKtDLrR92Ycb6oAti82z8fgsADw4Q5J/z8A+EjQCVE3abQ5q9DZqRDyxw3OymDI0XtQR64dUVmJnNTr5WgMJnVCguiX9iO0AZFAdPEXFm5u2OnNASDa8s5vPKBK51b4V70kybw1xa7tWSg/uZAAAA==",
    "origin": "library"
  },
  {
    "slug": "ls-bride-blusher",
    "src": "/images/ls-bride-blusher.webp",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAADQBACdASoUABsAPu1usFIppiSiqAgBMB2JQBYdgXOEJLINcJw/DkMY3OPnUN3vUAD+u1CNTgljEahWSHhQwTpduIGPhBZ1C1AoXFo/eXqvYWlFRVXclAehGuHM02oJFKut6PnS0w3RrkMZwLTbT6qF+i5pu3E/5NExshl/7/WTPWGvPreIfok3fybCa85hYO3X96KlO+FUtkvvwe2cl1C9yHxJsAAA",
    "origin": "theme"
  },
  {
    "slug": "ls-bride-cathedral",
    "src": "/images/ls-bride-cathedral.webp",
    "width": 1400,
    "height": 2100,
    "blurDataURL": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAADQBQCdASoUAB4APu1osFAppaUiqAqpMB2JYwCo9DTwrhajFZ5JQyIr4a2k7A1TF4oewB7lRYBAAP7Um5BFbenXO+M4tjIen54eNV10DVcSKSuNMpnlexYWf+jZTs3KG8ApHYEq9/J6ijSV1dFzIXT0noM7iZsYXo4DzH9nvfU8GIPxZPknKWH9nchK26AEZKbjqFwNEDGVGpxtxvMWB0gvkZ4P9uBLA2HfM0cVl9wSJjK3xOvyXXyx5veh3hFkZD7l0xc1w0RowZ1BrVDXeIhpt4edk8AA",
    "origin": "theme"
  },
  {
    "slug": "ls-cathedral",
    "src": "/images/ls-cathedral.webp",
    "width": 1200,
    "height": 1800,
    "blurDataURL": "data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAABwBQCdASoUAB4APu1kqk2ppaQiMAgBMB2JZQCo9Y0Wu5jfSM6zV4FjuehZGqk6+pp3jVNAAMyW56TdvMhHf2yHFFhuPxaCMFNVGrRS+jGRZJDiUr3wT7wX7dTPD7qzvRlT+0paMLiWJyJEM9PDwnczoRXJwaC6H17nHhQEhbmctNBxbXqraqw26pcLZbhdDaVR1mU+yVxFwYkV2W6+2VVZddQR5vteUL7+Ft417k/TSt27OdKBjf+ecyKR2ZqztzaeL/NKs72mhjxCwM/fGzaLD7ZedKlQGlMAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-ceremony",
    "src": "/images/ls-ceremony.webp",
    "width": 1400,
    "height": 1867,
    "blurDataURL": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAADwBACdASoUABsAPu1qr1AppaSiqAqpMB2JYwC06A4pu0WbXkF1OBAgnUY9dNZk9sAA/SEgd2HxPCnwRC6DmZaLdkeUXlsawT2G5PQsS8lrM11FQyu2HCQwfnmQlqUMhR+BZquV4rg2K+1rQNJ2avdP3FVOtpJ1IKGN6vcLeRUKMZPMZltsh32ZYe3PyVy6MLIUUr6Il0+/lGljg4LwsfqwpegBqMpAAAA=",
    "origin": "theme"
  },
  {
    "slug": "ls-church-veil",
    "src": "/images/ls-church-veil.webp",
    "width": 1284,
    "height": 1925,
    "blurDataURL": "data:image/webp;base64,UklGRuIAAABXRUJQVlA4INYAAAAQBQCdASoUAB4APu1urlKppiQiqAgBMB2JYwDBzYxiUUWYesYefWljW+ReA4+VgQkAAP6t0VmT2frdcni+2b406+OmreADbXAE63oSTVAO4jVUPeBkjTz1M/xlz3KyscpH2zCRhkFMAdnIvhnLteSZYPynNRy+AH7cbN6wUuc2XamFT2BrHcmHZPnnaiZxzPzpTY8PIJ+7bvVv752aZhDUz24mY2SfnSnyWHrNQRwCJYw/O0vWPabwymTD0MD1gOXbwxKlwSGP5bO17SzFf5+M/pC6AAAA",
    "origin": "theme"
  },
  {
    "slug": "ls-cobblestone",
    "src": "/images/ls-cobblestone.webp",
    "width": 1000,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRsQAAABXRUJQVlA4ILgAAABQBQCdASoUABwAPu1mpU4ppaMiMBgMATAdiWUAxkANDzFAMlsO8p5SbBAhm/fzFUEA2QAA8/kt2K9t9v/xW2kMGzA7Y9eHPrbfMoIlSfDCWglYMBlkU6SjupbTB2LmtVZdHh76/hLZTDJdS7HjY8NOUbU1RhQt9oikAoBSCCvWMCPk9CWk6fo3+mQx/nAdFr3jJRK+OCTF5OoSU5SxjyaRyoWimb5a2j7wbQdVm2W0mSvtGIt9ZQAA",
    "origin": "theme"
  },
  {
    "slug": "ls-couple",
    "src": "/images/ls-couple.webp",
    "width": 900,
    "height": 1200,
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAACQBQCdASoUABsAPu1sq1EppaOiqAqpMB2JYwCdAy6owYucMi4/EgCMOKfgMgs5wU0sk6fs4AD+eRhUocdBnWZGpZ/vkwzU1I3vEre8sIVF8n83Ople2+a01hs5xScNgdGxNfmXheAFCZ5Jcgz0WOTeYAxU7TM7LBJVK8yJWAf20YB+0U/J2tVuCRqHhC2S9ZAa1yOTaETp1GwQcf2LDjmRr2bL0icr6PoAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-embroidery",
    "src": "/images/ls-embroidery.webp",
    "width": 1100,
    "height": 2384,
    "blurDataURL": "data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAAAwBQCdASoUACwAPt1gpE2opiOiNVgMARAbiWcAADnW0JRAOdPoO/uN/FQv/L+7lVchAAD+EXPcwef8e0ECM3d6uxHOq4DZatuW5ivZBJbG1gzKl1HLdPeR96jM2S8khZNdaYunX2O9J1nLkM9GSrLH1TVK/W6xQl3fTgx5xogAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-golden-lace",
    "src": "/images/ls-golden-lace.webp",
    "width": 1200,
    "height": 1799,
    "blurDataURL": "data:image/webp;base64,UklGRgABAABXRUJQVlA4IPQAAAAQBgCdASoUAB4APu1iqE2ppaOiMAgBMB2JZgCdMzQ+CEABUDHoHzSdokRq4VcNluW94SOlNScgrwAA+D4xjQGFy+VJKNXk53dQwLYhDRHc6ys/ANo41dtAGOk9gJU4YiQEk79UXhwC5bsZK7WfNiKVNs9C/701DP7mrtCZkxm6dky9HiFFHIweJhZCIvYwLymIydlA/oG3nTGOyF8wjzFnsgWK86HTP1kPFJRVPJBMqtUZOc3x0wxgnQ0K8AUu+3h82ge3TSwaRVm5/guYLhQaxaYQnPRUcGXKy7Ta19JZpeeIYxXXUunF4Ckx9EcoY+rAAAAA",
    "origin": "theme"
  },
  {
    "slug": "ls-hero",
    "src": "/images/ls-hero.webp",
    "width": 1600,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAAAQBgCdASoUAB4APu1orE+ppiQiMBgIATAdiWMAsR8YqQFdFx0LPXJdoezgIwUwvi4fWVwJdh98vQAA/tOVLSIPeUi1PPWuo3RX9t6PutVrTXYfXyA4dgpIFxsOAaQCT2glbhnC9UDlM9aWNN49IFnr9aHfT1fqsmoqkU2ZfSeRSiM044Mjgd1A9qzTNihGqc6G+PloZ7kCzldFySi5AcXs2bK2dMOgbYAzT+x1GJKPIzAnFKWmWjOwWTzIGKQ8slorOe0J2WYGt48JawAAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-lace-closeup",
    "src": "/images/ls-lace-closeup.webp",
    "width": 1100,
    "height": 1467,
    "blurDataURL": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAACwBACdASoUABsAPu1iq1AppSOisBgIATAdiWkAAA2ppXuTwLlv0lWDVO02AwEAAPDhDkn/PwD4SNAJUSmGzc4AjpMmuV/gJ7wqZ+/3NdvqKQ9lxhxKJ7Nfo8BL5SQHRLAaG5vFzzdyTdui3RBswf7iKw7JRBcR4xQS6HtU6L8BCMaf8L7CZ/xgAAA=",
    "origin": "theme"
  },
  {
    "slug": "ls-mantilla-couple",
    "src": "/images/ls-mantilla-couple.webp",
    "width": 1400,
    "height": 933,
    "blurDataURL": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAACwBACdASoUAA0APu1iqU2ppaOiMAgBMB2JZACdMoGv/jeAGaDrD4ls1loYIomAAP7ri7jADaYqnzim31Rc9vRO0tqzt9F8ohLNi2fwE0D2Bad4QmBiCkJ2obZaZ0ii13R6q9vAVe0NfjHXUhtUSTbDSjS/Zm10Wtjs8ybTj9H3uG+w/UzbCMhHnlAHGYhHP2cx4xL/sj7CmHD5OmpWHYwA",
    "origin": "theme"
  },
  {
    "slug": "ls-mirror",
    "src": "/images/ls-mirror.webp",
    "width": 900,
    "height": 1349,
    "blurDataURL": "data:image/webp;base64,UklGRtoAAABXRUJQVlA4IM4AAABQBQCdASoUAB4APu1oq08ppiOiMBgIATAdiWkAAI1lFKP0qepvytjtedkTiL9fLG94oIAA/upVoXbJLkuagvpfowqZOYvTXVranACv1wpNldD11MAK89otG5DhI3VnE1mmDh45JWfoDI+h8IGMC1iV9AlyusoXF1B4eOw+Ylv5iXxJczL8aZHq39ryWTvFcJ2pahrNAV0eAdv/sb1PmB6skcsviXDpGIn2UONa0fyqmnQyfmT0NWnjibiwKty/3sUu69g1LSOZWH0yBQAAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-portrait-bw",
    "src": "/images/ls-portrait-bw.webp",
    "width": 1200,
    "height": 1463,
    "blurDataURL": "data:image/webp;base64,UklGRrYAAABXRUJQVlA4IKoAAABwBACdASoUABgAPu1ur1IppiQiqAgBMB2JaQAAJ/3k7tt2pbNs1aletU+YAAD+8Og/vVyLV63Gulp8pa9o/YRZ04FIMnI5gUPkHJeu2JjVT4jbBeWpLvMkxwbeAoINKfjT0mTj6sCv1vr4ekAa/LtTsLzT36boyXazch0VXv9+q2S6SkQmmXJHwVtjdf6O/AoKvWtobB65T40hMNV+UeiYwI3pM9nlgBgAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-studio",
    "src": "/images/ls-studio.webp",
    "width": 1350,
    "height": 2400,
    "blurDataURL": "data:image/webp;base64,UklGRuwAAABXRUJQVlA4IOAAAACQBQCdASoUACQAPu1kqE8ppSOpqqwBMB2JZQDDrBXBueKZP7bKypQiEEdPZnsWH6YxfNjegAD+iDCxyTiXwx8MyhYqGPo/PInAbrqzAhizMN3Fvu9oMioyPNomBuVL/UYIyp02/lAjzw0+qLQ0WACtnRl6sur39MGN5tiS6ndmdMJzEhhQoAFFqLndMOQGesUzK+3RYJwcn1wLGwzrAtSYusLB+kBmKRb2qRYfgI7IitynDhYQpkx6nJ2lJT6DTm5RqRDzuuiko1py0gRVoBU3vyqIe/Bs6xQcFntIxAAAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-veil-back",
    "src": "/images/ls-veil-back.webp",
    "width": 1200,
    "height": 1799,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwBACdASoUAB4APu1krE+ppSQiMBgIATAdiWcAy6Q0YZxYTA0AIMBOxc/jPAD+u67oKzzE5IIQti4xx8aX23FYXOnUYTHth7A8tfB1MLJOj2qdKSimRev0+EPkRG91RmxihSVoLeyNNBrwYA7yRZ3GVoR/h1OzcaoAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-veil-bw",
    "src": "/images/ls-veil-bw.webp",
    "width": 1200,
    "height": 1799,
    "blurDataURL": "data:image/webp;base64,UklGRs4AAABXRUJQVlA4IMIAAACQBQCdASoUAB4APu1srFEppiQiqAqpMB2JaQAD51DwSk7iDE1ydQC9sWYFcPTdcHsLQV2AQAD+bP8w6+btMDAADoJAZep2dVW5DECuKIYTd3XUo5pmEC0+fzjI7O7oFlz/Wj5TzQsCkyP4Tap4wQilPL7OgLgZb8LvduJI2rNFn5SkUcsSacN6jy0FHxSYan7ifmoi8OWPz0uZfx+BsonUMMYtqGE9U5nXkSzZxh+7pi7Jw/etEIOkK/oPOvJ0AAAAAA==",
    "origin": "theme"
  },
  {
    "slug": "ls-walking",
    "src": "/images/ls-walking.webp",
    "width": 1400,
    "height": 2100,
    "blurDataURL": "data:image/webp;base64,UklGRtYAAABXRUJQVlA4IMoAAABQBQCdASoUAB4APu1mqk2ppaQiMAgBMB2JYwDI1YyA32mDAXL2xgOH3uzFPW51WlhnMAAA/vHE6Dex42+pqZzyzHuHFonp4drGuhJsMy7RSPPeumZC3wdYh4TOs0+6zH1t3m1KliIZJ571MlbcQGx2+Nvyh8JE/VxCDX6TXlSLr+qCwCc+Yrv3L3OxdHiQaQ+ymrMari4nVFYozCUHuRLfT5yGriFT0DY40+CYZE8zaAsbR00PGerI1nXy1fsJniGkLOoiX8OfAAAA",
    "origin": "theme"
  }
] as const satisfies readonly GeneratedImage[];
