/**
 * Photography pipeline.
 *
 * Reads the curated set from reference/ and writes web-ready WebP into
 * public/images/, plus a tiny LQIP for each so no image slot ever renders
 * empty or shifts layout.
 *
 * Deliberately excluded (see docs/source-audit.md): five files in the drive
 * library are phone screenshots rather than photography — IMG_4651/4656/4657
 * carry a status bar and Instagram's comment UI, IMG_5004/5005 are a file
 * viewer with the filename in the header. They are not brand assets.
 *
 *   node scripts/build-images.mjs
 */
import { mkdir, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

import sharp from "sharp";

const REFERENCE = ["reference/theme/assets", "reference/images"];
const OUT = "public/images";

// Long-edge cap. The originals run to 8004x12000, which is far beyond
// anything a browser needs and would make next/image do pointless work.
const MAX_EDGE = 2400;
const QUALITY = 78;

const EXCLUDE = new Set([
  "IMG_4651.PNG",
  "IMG_4656.PNG",
  "IMG_4657.PNG",
  "IMG_5004.PNG",
  "IMG_5005.PNG",
  // Not photography — a reviews screenshot composite from the old theme.
  "ls-reviews.png",
]);

const IMAGE_EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);

/** `IMG_7030.JPG` → `img-7030`, `ls-bride-cathedral.jpg` → `ls-bride-cathedral` */
function slugify(filename) {
  return path
    .basename(filename, path.extname(filename))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

async function main() {
  await mkdir(OUT, { recursive: true });

  const manifest = [];

  for (const dir of REFERENCE) {
    let entries;
    try {
      entries = await readdir(dir);
    } catch {
      console.error(
        `! ${dir} missing — run: git checkout origin/source-assets -- source`,
      );
      process.exitCode = 1;
      return;
    }

    for (const name of entries.sort()) {
      if (!IMAGE_EXT.has(path.extname(name).toLowerCase())) continue;
      if (EXCLUDE.has(name)) {
        console.log(`  skip  ${name}  (excluded)`);
        continue;
      }

      const slug = slugify(name);
      const source = path.join(dir, name);

      // `rotate()` with no argument applies the EXIF orientation and then
      // strips it — without this, phone photos land sideways once metadata
      // is dropped.
      const pipeline = sharp(source, { limitInputPixels: false }).rotate();
      const meta = await pipeline.metadata();

      const width = meta.width ?? 0;
      const height = meta.height ?? 0;
      const scale = Math.min(1, MAX_EDGE / Math.max(width, height));
      const outWidth = Math.round(width * scale);
      const outHeight = Math.round(height * scale);

      await pipeline
        .clone()
        .resize(outWidth, outHeight, { withoutEnlargement: true })
        .webp({ quality: QUALITY, effort: 5 })
        .toFile(path.join(OUT, `${slug}.webp`));

      // 20px-wide blur placeholder, inlined as a data URI in the manifest.
      const lqip = await pipeline
        .clone()
        .resize(20)
        .webp({ quality: 40 })
        .toBuffer();

      manifest.push({
        slug,
        src: `/images/${slug}.webp`,
        width: outWidth,
        height: outHeight,
        blurDataURL: `data:image/webp;base64,${lqip.toString("base64")}`,
        origin: dir.includes("theme") ? "theme" : "library",
      });

      console.log(
        `  ok    ${slug.padEnd(40)} ${outWidth}x${outHeight}`.padEnd(60) +
          (scale < 1 ? `  (from ${width}x${height})` : ""),
      );
    }
  }

  manifest.sort((a, b) => a.slug.localeCompare(b.slug));

  await writeFile(
    "content/images.generated.ts",
    `// GENERATED by scripts/build-images.mjs — do not edit by hand.\n` +
      `// Alt text and focal points live in content/images.ts, which reads this.\n\n` +
      `export type GeneratedImage = {\n` +
      `  slug: string;\n  src: string;\n  width: number;\n  height: number;\n` +
      `  blurDataURL: string;\n  origin: "theme" | "library";\n};\n\n` +
      `export const GENERATED_IMAGES = ${JSON.stringify(manifest, null, 2)} as const satisfies readonly GeneratedImage[];\n`,
  );

  console.log(`\n${manifest.length} images → ${OUT}/ + content/images.generated.ts`);
}

await main();
